version: '3.1'
services:
  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: "bestbook"
      MYSQL_USER: "bestbook"
      MYSQL_PASSWORD: "1bestbook!"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"

  config:
    build: config
    image: bestbook/config
    restart: always
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    build: registry
    image: bestbook/registry
    restart: always
    ports:
      - 8777:8777
    depends_on:
      - config
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    build: auth-service
    image: bestbook/auth-service
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - config
      - mysql
    logging:
      options:
        max-size: "10m"
        max-file: "10"
