version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: bestbook-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: on-failure

  mysql:
    image: mysql/mysql-server:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
    container_name: bestbook-mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: "bestbook"
      MYSQL_USER: "bestbook"
      MYSQL_PASSWORD: "1bestbook!"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]

  config:
    build: _config
    image: callmegary/bestbook-config
    container_name: bestbook-config
    ports:
      - 8888:8888
    restart: on-failure

  registry:
    build: _registry
    image: callmegary/bestbook-registry
    container_name: bestbook-registry
    ports:
      - 8777:8777
    restart: on-failure
    depends_on:
      config:
        condition: service_healthy

  gateway:
    build: _gateway
    image: callmegary/bestbook-gateway
    container_name: bestbook-gateway
    ports:
      - 4000:4000
    restart: on-failure
    depends_on:
      config:
        condition: service_healthy

  auth-service:
    build: auth-service
    image: callmegary/bestbook-auth-service
    container_name: bestbook-auth-service
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      config:
        condition: service_healthy
      mysql:
        condition: service_healthy

  book-service:
    build: book-service
    image: callmegary/bestbook-book-service
    container_name: bestbook-book-service
    ports:
      - 6000:6000
    restart: on-failure
    depends_on:
      config:
        condition: service_healthy
      mysql:
        condition: service_healthy

  notification-service:
    build: notification-service
    image: callmegary/bestbook-notification-service
    container_name: bestbook-notification-service
    restart: on-failure
    depends_on:
      config:
        condition: service_healthy
