version: '2.1'
services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: bestbook-mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: "bestbook"
      MYSQL_USER: "bestbook"
      MYSQL_PASSWORD: "1bestbook!"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]

  config:
    build: config
    image: guanlin84/bestbook-config
    container_name: bestbook-config
    restart: on-failure

  registry:
    build: registry
    image: guanlin84/bestbook-registry
    container_name: bestbook-registry
    restart: on-failure
    depends_on:
      config:
        condition: service_healthy

  gateway:
    build: gateway
    image: guanlin84/bestbook-gateway
    container_name: bestbook-gateway
    restart: on-failure
    ports:
      - 8080:4000
    depends_on:
      config:
        condition: service_healthy

  auth-service-1:
    build: auth-service
    image: guanlin84/bestbook-auth-service
    container_name: bestbook-auth-service-1
    restart: on-failure
    depends_on:
      config:
        condition: service_healthy
      mysql:
        condition: service_healthy

  auth-service-2:
    build: auth-service
    image: guanlin84/bestbook-auth-service
    container_name: bestbook-auth-service-2
    restart: on-failure
    depends_on:
      config:
        condition: service_healthy
      mysql:
        condition: service_healthy
