logging:
  level:
    org.springframework.security: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8777/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/auth/users/current

#spring:
#  rabbitmq:
#    host: rabbitmq