spring:
  jpa:
    database: MYSQL
    hibernate.ddl-auto: update

  datasource:
    url: jdbc:mysql://mysql:3306/bestbook
    username: bestbook
    password: 1bestbook!
    driver-class-name: com.mysql.jdbc.Driver

  jackson:
    default-property-inclusion: non_null

server:
  context-path: /uaa
  port: 5000


bestbook:
  rabbitmq:
    user:
      exchange-name: bestbook.user
      registered-queue-name: bestbook.user.registered