spring:
  jpa:
    database: MYSQL
    hibernate.ddl-auto: create

  datasource:
    url: jdbc:mysql://mysql:3306/bestbook
    username: bestbook
    password: 1bestbook!
    driver-class-name: com.mysql.jdbc.Driver

  jackson:
    default-property-inclusion: non_null

server:
  context-path: /auth
  port: 5000