security:
  oauth2:
    client:
      clientId: book-service
      clientSecret: 1book-service!
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  jpa:
    database: MYSQL
    hibernate.ddl-auto: update

  datasource:
    url: jdbc:mysql://mysql:3306/bestbook
    username: bestbook
    password: 1bestbook!
    driver-class-name: com.mysql.jdbc.Driver

  jackson:
    default-property-inclusion: non_null

server:
  context-path: /book
  port: 6000